module.exports = {
	apps: [
		{
			name: 'project-service',
			instances: 2,
			max_memory_restart: '4G',
			exec_mode: 'cluster',
			watch: false,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: 'localhost:27017',
				MONGODB_USER: '',
				MONGODB_PASS: '', 
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!_!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: '79',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'production',
			},
		},
		{
			name: 'dev_project-service',
			instances: 1,
			max_memory_restart: '8G',
			exec_mode: 'cluster',
			watch: true,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: 'localhost',
				MONGODB_USER: '',
				MONGODB_PASS: '', 
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!asdf!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: 'd',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'development',
			},
		}
	],
};
