module.exports = {
	apps: [
		{
			name: 'project-service',
			instances: 2,
			max_memory_restart: '4G',
			exec_mode: 'cluster',
			watch: false,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: '163.172.181.118',
				MONGODB_USER: 'rootAdmin',
				MONGODB_PASS: 'Kent260106@', // if have "@" must be using with encodeURIComponent(process.env.MONGODB_PASS);
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!KentKart2025!ProjectToken&2021%SaMonic@_Temple@_!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: '6379',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'production',
			},
		},
		{
			name: 'dev_project-service',
			instances: 2,
			max_memory_restart: '8G',
			exec_mode: 'cluster',
			watch: true,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: '163.172.181.118',
				MONGODB_USER: 'rootAdmin',
				MONGODB_PASS: 'Kent260106@', // if have "@" must be using with encodeURIComponent(process.env.MONGODB_PASS);
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!KentKart2025!ProjectToken&2021%SaMonic@_Temple@_!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: '6379',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'development',
			},
		},
		{
			name: 'test_project-service',
			instances: 2,
			max_memory_restart: '8G',
			exec_mode: 'cluster',
			watch: true,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: '163.172.181.118',
				MONGODB_USER: 'rootAdmin',
				MONGODB_PASS: 'Kent260106@', // if have "@" must be using with encodeURIComponent(process.env.MONGODB_PASS);
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!KentKart2025!ProjectToken&2021%SaMonic@_Temple@_!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: '6379',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'test',
			},
		},
		{
			name: 'local_project-service',
			instances: 2,
			max_memory_restart: '8G',
			exec_mode: 'cluster',
			watch: true,
			script: './index.js',
			ignore_watch: ['node_modules', '.git', 'data'],
			env: {
				AWS_ACCESS_KEY: '',
				AWS_SECRET_KEY: '',
				MONGODB_HOST: '127.0.0.1',
				MONGODB_USER: 'root',
				MONGODB_PASS: '', // if have "@" must be using with encodeURIComponent(process.env.MONGODB_PASS);
				MONGODB_PORT: '27017',
				JWT_SECRET_KEY: '!KentKart2025!ProjectToken&2021%SaMonic@_Temple@_!',
				REDIS_HOST: '',
				REDIS_PASS: '',
				REDIS_PORT: '6379',
				MAILGUN_APIKEY: 'test',
				NODE_ENV: 'local',
			},
		},
	],
};
